### ISSUE TITLE
Fix keypressobservers

### ISSUE THREAD

**Issue by rossengeorgiev** [onuraslan/DotaBuffCP#13]
This repo looks out of data, but I am openning the issue anyway. The implementation of `KeypressObservers` is not cross-browser compatible. The code is located in `picker-angular.js` and here is a fix.

```javascript
KeypressObservers = [];
jQuery(document).on('keypress', function(e){
	for (var N = 0; N < KeypressObservers.length; N++)
		KeypressObservers[N](e.which || e.keyCode);
});
```

**Comment by onuraslan** [comment]
Hi. Thanks for reporthing. But I am not sure I understand the issue and your fix.

This project is not using angular. It's using backbone.js and I am using backbone events.

**Comment by rossengeorgiev** [comment]
Right. My mistake, I came here from http://dotapicker.com/counterpick.php, but apparently that's not the same project.
