### ISSUE TITLE
Add Oracle?

### ISSUE THREAD

**Issue by tkiethanom** [onuraslan/DotaBuffCP#9]
Add Oracle?

**Comment by Anaron** [comment]
Why hasn't Oracle been added yet?

**Comment by vichug** [comment]
i think it's because the project isn't maintained anymore, there is another similar things that has added Oracle https://github.com/onuraslan/DotaBuffCP/issues/7

**Comment by onuraslan** [comment]
Looks like other website I mentioned in #7 completely changed. I will try to update database as soon as I find time.

**Comment by onuraslan** [comment]
It's updated now: (Closes: #9, #11)
